### ISSUE TITLE
ROS 2 Release

### ISSUE THREAD

**Issue by henningkayser** [ros-industrial/stomp#5]
Hi @Levi-Armstrong, I've been working on a lean MoveIt 2 plugin adaption of STOMP (https://github.com/ros-planning/stomp_moveit) and would like to complete it and get a release out. Would you mind blooming STOMP for ROS 2 Rolling, possibly Humble? I would greatly appreciate it.

**Comment by Levi-Armstrong** [comment]
I don't think I have permission, but @marip8 should be able to help.

**Comment by marip8** [comment]
I can release it. @Levi-Armstrong this package hasn't been released before has it? It doesn't appear to have a release repository on the `ros-industrial-release` organization

**Comment by Levi-Armstrong** [comment]
It has not

**Comment by marip8** [comment]
It looks like I need to release `ros_industrial_cmake_boilerplate` since this package depends on it. I just finished that for Humble and rolling, but I'm not sure if we need to wait for those to get merged and be available before we proceed with the release of this package. Any thoughts?

**Comment by gavanderhoorn** [comment]
It used to be the case Bloom could only resolve unreleased dependencies within the same repository when releasing a dependent.

I've not seen any changes that would make that no longer a limitation -- but I also haven't checked recently.

> I'm not sure if we need to wait for those to get merged and be available before we proceed with the release of this package

That would mean you'd have to wait for all the dependencies to be merged and available, yes -- at least in the `testing` repository.

**Comment by marip8** [comment]
> Btw: I noticed you created a release repository for stomp in ros-industrial-releases. Current 'best practice' for releasing ROS 2 packages is to make use of [ros2-gbp](https://github.com/ros2-gbp). Did you deliberately choose not to do that?

No; I haven't released a package for ROS2 yet, so I was unaware of ros2-gbp. I haven't done anything meaningful with that repo I created, so I can delete it. It looks like a `ros-industrial` team already exists with @Levi-Armstrong as the sole member. Should I request to be added to that team and request for this repo's release repository to be added under that team?

I also just released a new version of `ros_industrial_cmake_boilerplate` today using the release repository in `ros-industrial-release` for `rolling`, `foxy`, and `humble`. Should those be closed and managed through the release repository in `ros2-gbp`?

**Comment by gavanderhoorn** [comment]
> Should I request to be added to that team and request for this repo's release repository to be added under that team?

if we want to 'play nice' and align ourselves with ROS 2 release practices then it would make sense to do that, yes.

Please add other ROS-Industrial owners / releasers as well.

The main motivation for setting up that centralised infrastructure is to:

 - make it easier to script releases into Rolling and cutting new ROS distros from Rolling
 - always have the possibility to take over / reassign / revive maintainership of packages, or at least be able to have a way to keep control over release repositories even if original authors/maintainers disappear

Since most of the repositories we're considering here are already maintained -- or at least accessible -- by a team, the second would be less of a thing for us I believe.

The first could be nice, but personally I'm not too interested in it.

> I also just released a new version of `ros_industrial_cmake_boilerplate` today using the release repository in `ros-industrial-release` for `rolling`, `foxy`, and `humble`. Should those be closed and managed through the release repository in `ros2-gbp`?

See above.

If we want to keep things under our own control, then we could keep releasing in the same way as we've always done.

If we feel the rationale for `ros2-gbp` makes sense, those PRs should be closed, yes.

**Comment by marip8** [comment]
Closing; I just opened PRs for release into `rolling`, `humble`, and `foxy` so this should be available soon

**Comment by henningkayser** [comment]
Awesome, thank you!
